export const routes = {
    DEFAULT: "/",
    DASHBOARD:"/Home",
    ERROR:"*",
    FAQS:"/Faqs",
    CONTACT:"/contact",
    PROFILE:"/Profile",
    EDITPROFILE:"/EditProfile",
    TERMSCONDITIONS:"/TermsConditions",
    BANNERS:"/Banners",
    LEGALCOMPLIANCES:"/LegalCompliances",
    ABOUTUS:"/AboutUs",
    PLATFORM:"/Platform",
    HELPCENTER:"/HelpCenter",
    TRADEFEE:"/TradeFee",
    USER:"/User",
    Videos:"/Videos",
    CHANGEPASSWORD:"/ChangePassword",
    FORGOTPASSWORD:"/ForgotPassword",
    REPORT:"/Report",
    PRIVACYPOLICY:"/PrivacyPolicy",
    TRADECURRENCY:"/TradeCurrency",
    NOTIFICATION:"/Notification"
};